### PR TITLE
[sync-actions] Fix changing prices and matching existing variants

### LINKED ISSUE #871: Price importer: " Duplicate price scope" error
### Support reference number

https://jira.commercetools.com/browse/SUPPORT-4096

### Description

Given a CSV import file with no duplicate prices (rows). 
When importing this file on the price importer
Then an Error is  thrown up for Duplicate price scope

`statusCode: 400,
  code: 400,
  stack: 'BadRequest: Duplicate price scope: (currency: EUR). The combination of currency, country, customerGroup and channel must be unique for each price of a product variant.\n    at /app/node_modules/sphere-product-import/node_modules/sphere-node-sdk/lib/services/base.js:508:22\n    at ProductService.BaseService._wrapResponse (/app/node_modules/sphere-product-import/node_modules/sphere-node-sdk/lib/services/base.js:523:11)\n    at /app/node_modules/sphere-product-import/node_modules/sphere-node-sdk/lib/services/base.js:400:40\n    at Request._callback (/app/node_modules/sphere-product-import/node_modules/sphere-node-sdk/lib/connect/rest.js:166:14)\n    at Request.self.callback (/app/node_modules/sphere-product-import/node_modules/request/request.js:360:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/app/node_modules/sphere-product-import/node_modules/request/request.js:1202:14)\n    at emitOne (events.js:121:20)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/app/node_modules/sphere-product-import/node_modules/request/request.js:1150:12)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)' } 'Skipping product due to an error'
.info:    Wrapped 5 price(s) into 1 existing product(s).
error:   { message: 'Duplicate price scope: (currency: EUR). The combination of currency, country, customerGroup and channel must be unique for each price of a product variant.',`

### Expected Behavior

The prices are imported successfully.

### Current Behavior

Price import was unsuccessful with the error "Duplicate price scope"

### Context

The customer is unable to update the prices

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Fixes #871 

#### Description

This PR fixes how we match existing variants when syncing prices.
There was a problem that when a new and all existing variants have key `undefined`, we incorrectly match this new variant with the first existing variant because we compare `newVariant.key` (`undefined`) againts `existingVariant.key` (`undefined`)

#### Todo

- Tests
  - [x] Unit
  - [ ] Integration
  - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: packages/sync-actions/src/utils/create-build-actions.js [hunk 1]
```diff
@@ -35,9 +35,10 @@ function injectMissingPriceIds(nextVariants, previousVariants) {
     if (!prices) return restOfVariant
     const oldVariant = previousVariants.find(
       previousVariant =>
-        previousVariant.id === newVariant.id ||
-        previousVariant.key === newVariant.key ||
-        previousVariant.sku === newVariant.sku
+        (!isNil(previousVariant.id) && previousVariant.id === newVariant.id) ||
+        (!isNil(previousVariant.key) &&
+          previousVariant.key === newVariant.key) ||
+        (!isNil(previousVariant.sku) && previousVariant.sku === newVariant.sku)
```
Comment (daern91) [inline packages/sync-actions/src/utils/create-build-actions.js]: Why not simply like below?
```
(previousVariant.id && previousVariant.id === newVariant.id) ||
(previousVariant.key && previousVariant.key === newVariant.key) ||
(previousVariant.sku && previousVariant.sku === newVariant.sku)
```

Comment (junajan) [reply packages/sync-actions/src/utils/create-build-actions.js]: This was mainly because of id - if we start indexing from zero, we would not match variants with `id` equal to `0`
