### PR TITLE
fix(product-json-to-xlsx): add missing CLI parameter

### LINKED ISSUE #834: [product-json-to-xlsx] Add missing parameter - onlyMasterVariants
### Support reference number
In the new XLSX product mapper, we are missing `onlyMasterVariants` CLI parameter

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Fixes #834 

Note: This feature is tested already in `product-json-to-csv`

### CODE REVIEW

File: packages/product-json-to-xlsx/src/cli.js [hunk 1]
```diff
@@ -201,6 +206,7 @@ Promise.all([getHeaders(args), resolveCredentials(args)])
       fillAllRows: args.fillAllRows,
       language: args.language,
       multiValueDelimiter: args.multiValueDelimiter,
+      onlyMasterVariants: args.onlyMasterVariants,
```
Comment (daern91) [inline packages/product-json-to-xlsx/src/cli.js]: Maybe we should also add this here? https://github.com/commercetools/nodejs/blob/c7daa22c81415497cfc8041360ade51e4dd1d58a/packages/product-json-to-xlsx/test/main.spec.js#L19

Comment (junajan) [reply packages/product-json-to-xlsx/src/cli.js]: It has a default value `onlyMasterVariants = false` so it worked even without it.
I added it to be more clear + it wanted also to bump flow version 0d744ef
