### PR TITLE
fix(http-middleware): fix host url. works with or without ending slash

### LINKED ISSUE #67: SDK middleware fails when given a host that ends with a slash
### Description
Passing `https://api.sphere.io/` vs. `https://api.sphere.io` makes a difference.

### Expected Behavior
Both should work the same.

### Current Behavior
My guess is it ends up with a double slash when appending things to the host URL.

### Context
I used the URLs that are given at the dev.commercetools.com documentation which failed. Confirmed this for `sdk-middleware-http`.

### Possible Solution
Merge slashes if needed.

### PR DESCRIPTION
**Pull request by wizzy25**
affects: @commercetools/sdk-middleware-http

fixes #67

#### Summary

resolve host url. works with or without ending slash

#### Description

 host url gets parsed properly whether
 it ends with slash or not

#### Todo

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: packages/sdk-middleware-auth/src/client-credentials-flow.js [hunk 1]
```diff
@@ -20,8 +20,7 @@ type Task = {
 }
 
 export default function createAuthMiddlewareForClientCredentialsFlow (
-  options: AuthMiddlewareOptions,
-): Middleware {
```
Comment (emmenko) [inline packages/sdk-middleware-auth/src/client-credentials-flow.js]: Keep the same formatting

File: packages/sdk-middleware-auth/test/client-crendentials-flow.spec.js [hunk 2]
```diff
@@ -97,6 +97,7 @@ describe('Client Crentials Flow', () => {
       )
       nock(middlewareOptions.host)
         .filteringRequestBody(/.*/, '*')
+        // Check hear
```
Comment (emmenko) [inline packages/sdk-middleware-auth/test/client-crendentials-flow.spec.js]: ??

File: package.json [hunk 3]
```diff
@@ -120,5 +120,8 @@
         "babel-module": {}
       }
     }
+  },
+  "dependencies": {
+    "normalize-url": "^1.9.0"
```
Comment (emmenko) [inline package.json]: Let's not introduce unnecessary dependencies please.

You can simply fix this "problem" with a `replace(/\/$/, '')`

```js
'foo/'.replace(/\/$/, '')
// "foo"
'foo'.replace(/\/$/, '')
// "foo"
```

File: packages/sdk-middleware-http/package.json [hunk 4]
```diff
@@ -31,7 +31,8 @@
     "build:umd:min": "cross-env NODE_ENV=production webpack --config ../../webpack.config.js --output-library CommercetoolsSdkMiddlewareHttp --output-library-target umd src/index.js dist/commercetools-sdk-middleware-http.min.js"
   },
   "dependencies": {
-    "isomorphic-fetch": "2.2.1"
+    "isomorphic-fetch": "2.2.1",
+    "normalize-url": "^1.9.0"
```
Comment (emmenko) [inline packages/sdk-middleware-http/package.json]: Remove

File: packages/sdk-middleware-http/src/http.js [hunk 5]
```diff
@@ -19,7 +21,7 @@ export default function createHttpMiddleware (
   options: HttpMiddlewareOptions,
 ): Middleware {
   return next => (request: MiddlewareRequest, response: MiddlewareResponse) => {
-    const url = options.host + request.uri
+    const url = normalizeUrl(options.host + request.uri)
```
Comment (emmenko) [inline packages/sdk-middleware-http/src/http.js]: See comment https://github.com/commercetools/nodejs/pull/74/files#r99773653

File: package.json (hunk 3 above)
Comment (wizzy25) [inline package.json]: This would assume that the uri always begins with a slash, which may not always be the case

Comment (emmenko) [inline package.json]: We should make it a rule then (e.g. validation)

File: package.json [hunk 6]
```diff
@@ -121,5 +121,6 @@
         "babel-module": {}
       }
     }
-  }
+  },
```
Comment (hisabimbola) [inline package.json]: You can remove the `dependencies` field since it's empty. No need to commit it.

File: packages/sdk-middleware-auth/test/build-requests.spec.js [hunk 7]
```diff
@@ -31,6 +31,28 @@ describe('buildRequestForClientCredentialsFlow', () => {
     })
   })
 
+  it('parses a host that ends with \'/\'', () => {
```
Comment (hisabimbola) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: To make this more readable I would prefer you use backtick _`_ and quotes to emphasise the forward slash

**Comment by wizzy25** [comment]
I think it should be good enough for a merge now?

**Comment by emmenko** [comment]
BTW: there are eslint errors, but you shouldn't have been able to commit. How is that possible?

File: packages/sdk-middleware-auth/test/build-requests.spec.js (hunk 7 above)
Comment (wizzy25) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: @emmenko The eslint errors are because I replaced ```'``` with ``` ` ``` to avoid escaping and make the code more reasonable (I forced the commit)
Would replace ```/``` with ```"slash"``` to maintain readability and lintability... Then everyone should be happy 😋

Comment (emmenko) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: I mean, you shouldn't have been able to commit since we have git hooks setup. Did you actually set them up correctly?

Comment (wizzy25) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: I forced the commit with ```--no-verify``` flag

Comment (emmenko) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: :man_facepalming: what's the point then of having the commit hooks? 😅

Try to avoid then, unless it's really necessary please.

Comment (wizzy25) [inline packages/sdk-middleware-auth/test/build-requests.spec.js]: 😃😃🙏🏾

**Comment by emmenko** [comment]
Alright, let's go ahead and merge this. Good job guys! 👍

**Comment by hisabimbola** [comment]
@wizzy25 Please squash and merge and remember to use `fix` so that a release can be triggered.

**Comment by emmenko** [comment]
And `affects`. Read https://github.com/commercetools/nodejs/blob/master/CONTRIBUTING.md#releases

**Comment by Siilwyn** [comment]
Or just do `git reset --soft HEAD~9 && npm run commit` ;)
No way for human errors that way.

**Comment by hisabimbola** [comment]
@wizzy25 Please delete the branch when you done merging to avoid old branches flying 🚡  around

**Comment by emmenko** [comment]
The release commit was wrong, there should be only one "affects" line with comma separated list of packages. Now only http got release.
This is one of the reasons I have doubts about using semantic releases.

Anyway, no worries and just keep in mind this for the future ;)
