### PR TITLE
77 clean up flow types

### LINKED ISSUE #77: Clean up flow types
### Description
The amount of flow type warnings are building up making it very hard to see new warnings and making me sad when running the linting task. :(

```
 packages/api-request-builder/src/build-query-string.js:26:49
  ⚠   26:49  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   26:49  Missing "e" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠   45:49  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   45:49  Missing "s" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠   58:19  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   58:19  Missing "f" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠   59:20  Missing "f" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠   59:20  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   60:27  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   60:27  Missing "f" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠   61:28  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   61:28  Missing "f" parameter type annotation.                                      flowtype/require-parameter-type

  packages/api-request-builder/src/create-request-builder.js:13:42
  ⚠   13:42  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   13:43  Missing "acc" parameter type annotation.                                    flowtype/require-parameter-type
  ⚠   13:48  Missing "key" parameter type annotation.                                    flowtype/require-parameter-type

  packages/api-request-builder/src/create-service.js:53:23
  ⚠   53:23  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   53:24  Missing "acc" parameter type annotation.                                    flowtype/require-parameter-type
  ⚠   53:29  Missing "feature" parameter type annotation.                                flowtype/require-parameter-type

  packages/sdk-client/src/client.js:34:27
  ⚠   34:27  Missing "resolve" parameter type annotation.                                flowtype/require-parameter-type
  ⚠   34:36  Missing "reject" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   68:27  Missing "resolve" parameter type annotation.                                flowtype/require-parameter-type
  ⚠   68:36  Missing "reject" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠  125:24  Missing return type annotation.                                             flowtype/require-return-type
  ⚠  125:24  Missing "func" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠  130:23  Missing return type annotation.                                             flowtype/require-return-type
  ⚠  130:24  Missing "a" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠  130:27  Missing "b" parameter type annotation.                                      flowtype/require-parameter-type
  ⚠  130:33  Missing return type annotation.                                             flowtype/require-return-type
  ⚠  130:34  Missing "args" parameter type annotation.                                   flowtype/require-parameter-type

  packages/sdk-middleware-auth/src/build-requests.js:44:3
  ⚠   44:3   Unexpected todo comment.                                                    no-warning-comments
  ⚠   48:3   Unexpected todo comment.                                                    no-warning-comments
  ⚠   52:3   Unexpected todo comment.                                                    no-warning-comments

  packages/sdk-middleware-auth/src/client-credentials-flow.js:29:10
  ⚠   29:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   29:10  Missing "next" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   92:35  Missing "task" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠  113:13  Missing "error" parameter type annotation.                                  flowtype/require-parameter-type

  packages/sdk-middleware-http/src/http.js:21:10
  ⚠   21:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   21:10  Missing "next" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   97:23  Missing "{ statusCode, message, ...rest }" parameter type annotation.       flowtype/require-parameter-type

  packages/sdk-middleware-logger/src/logger.js:9:10
  ⚠    9:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠    9:10  Missing "next" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   11:5   Unexpected console statement.                                               no-console
  ⚠   12:5   Unexpected console statement.                                               no-console

  packages/sdk-middleware-logger/test/logger.spec.js:21:28
  ⚠   21:28  Unexpected console statement.                                               no-console
  ⚠   26:5   Unexpected console statement.                                               no-console
  ⚠   31:5   Unexpected console statement.                                               no-console
  ⚠   51:14  Unexpected console statement.                                               no-console
  ⚠   52:14  Unexpected console statement.                                               no-console
  ⚠   56:14  Unexpected console statement.                                               no-console

  packages/sdk-middleware-queue/src/queue.js:35:10
  ⚠   35:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   35:10  Missing "next" parameter type annotation.                                   flowtype/require-parameter-type

  packages/sdk-middleware-user-agent/src/user-agent.js:18:10
  ⚠   18:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   18:10  Missing "next" parameter type annotation.                                   flowtype/require-parameter-type

  packages/sync-actions/src/categories.js:16:1
  ⚠   16:1   Missing return type annotation.                                             flowtype/require-return-type
  ⚠   16:36  Missing "mapActionGroup" parameter type annotation.                         flowtype/require-parameter-type
  ⚠   17:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   17:33  Missing "diff" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   17:39  Missing "newObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   17:47  Missing "oldObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   20:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   23:50  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   26:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   29:46  Missing return type annotation.                                             flowtype/require-return-type

  packages/sync-actions/src/customers.js:16:1
  ⚠   16:1   Missing return type annotation.                                             flowtype/require-return-type
  ⚠   16:36  Missing "mapActionGroup" parameter type annotation.                         flowtype/require-parameter-type
  ⚠   17:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   17:33  Missing "diff" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   17:39  Missing "newObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   17:47  Missing "oldObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   20:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   23:50  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   26:49  Missing return type annotation.                                             flowtype/require-return-type

  packages/sync-actions/src/inventories.js:16:1
  ⚠   16:1   Missing return type annotation.                                             flowtype/require-return-type
  ⚠   16:37  Missing "mapActionGroup" parameter type annotation.                         flowtype/require-parameter-type
  ⚠   17:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   17:33  Missing "diff" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   17:39  Missing "newObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   17:47  Missing "oldObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   20:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   23:50  Missing return type annotation.                                             flowtype/require-return-type

  packages/sync-actions/src/orders.js:17:1
  ⚠   17:1   Missing return type annotation.                                             flowtype/require-return-type
  ⚠   17:33  Missing "mapActionGroup" parameter type annotation.                         flowtype/require-parameter-type
  ⚠   18:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   18:33  Missing "diff" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   18:39  Missing "newObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   18:47  Missing "oldObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   21:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   24:50  Missing return type annotation.                                             flowtype/require-return-type

  packages/sync-actions/src/products.js:23:1
  ⚠   23:1   Missing return type annotation.                                             flowtype/require-return-type
  ⚠   23:35  Missing "mapActionGroup" parameter type annotation.                         flowtype/require-parameter-type
  ⚠   24:10  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   24:33  Missing "diff" parameter type annotation.                                   flowtype/require-parameter-type
  ⚠   24:39  Missing "newObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   24:47  Missing "oldObj" parameter type annotation.                                 flowtype/require-parameter-type
  ⚠   24:55  Missing "options" parameter type annotation.                                flowtype/require-parameter-type
  ⚠   28:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   31:44  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   34:50  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   37:48  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   40:50  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   44:46  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   47:46  Missing return type annotation.                                             flowtype/require-return-type
  ⚠   50:50  Missing return type annotation.                                             flowtype/require-return-type
```

To prevent this from happening in the future let's run ESLint on CI with `--max-warnings 0` so it fails.

### PR DESCRIPTION
**Pull request by Babanila**
#### Summary

Add missing flow types

#### Description

Add missing flow types to all packages so that all current problems(0 error, 180 warnings) are solved and new warnings can be seen.

Closes #77

### CODE REVIEW

File: packages/state-importer/src/main.js [hunk 1]
```diff
@@ -96,34 +96,36 @@ export default class StateImport {
...
-  processStream(chunk: Array<StateData>, cb: () => mixed) {
+  processStream(chunk: Array<StateData>, cb: () => mixed): Promise<mixed> {
     this.logger.debug(`Starting conversion of ${chunk.length} states`)
     return this._processBatches(chunk).then(cb)
     // No catch block as errors will be caught in the CLI
   }
 
   // Public function for direct module usage
-  run(states: Array<StateData>) {
+  run(states: Array<StateData>): StateData {
```
Comment (daern91) [inline packages/state-importer/src/main.js]: `Promise<any>`?

File: packages/state-importer/src/main.js [hunk 2]
```diff
@@ -96,34 +96,36 @@ export default class StateImport {
...
     return this._processBatches(states)
   }
 
-  _processBatches(states: Array<StateData>) {
+  _processBatches(states: Array<StateData>): Object {
```
Comment (daern91) [inline packages/state-importer/src/main.js]: `Promise<any>`?

File: packages/state-importer/src/main.js [hunk 3]
```diff
@@ -96,34 +96,36 @@ export default class StateImport {
...
     const predicate = StateImport._buildPredicate(states)
     const service = this._createService()
     const uri = service.where(predicate).build()
     const existingStatesRequest = StateImport._buildRequest(uri, 'GET')
     return this.client
       .execute(existingStatesRequest)
-      .then(({ body: { results: existingStates } }: Object) =>
+      .then(({ body: { results: existingStates } }: Object): Object =>
```
Comment (daern91) [inline packages/state-importer/src/main.js]: This one looks like a `Promise`?

File: packages/state-importer/src/main.js [hunk 4]
```diff
@@ -96,34 +96,36 @@ export default class StateImport {
...
         this._createOrUpdate(states, existingStates)
       )
-      .then(() => Promise.resolve())
-      .catch(error => {
+      .then((): Promise<any> => Promise.resolve())
```
Comment (daern91) [inline packages/state-importer/src/main.js]: This one cant be `any` when it literally resolves to undefined next to it.
`Promise.resolve()`

File: packages/state-importer/src/main.js [hunk 5]
```diff
@@ -136,21 +138,21 @@ export default class StateImport {
   _createOrUpdate(
     newStates: Array<StateData>,
     existingStates: Array<StateData>
-  ) {
+  ): Promise<any> {
```
Comment (daern91) [inline packages/state-importer/src/main.js]: Looks like a lot of Promise<any> here which should not be. We should expand a bit on it and not use generic `any` all over the place.

File: packages/state-importer/src/main.js [hunk 6]
```diff
@@ -202,21 +204,21 @@ export default class StateImport {
...
+  _create(state: StateData): Promise<any> {
     const service = this._createService()
     const uri = service.build()
     const req = StateImport._buildRequest(uri, 'POST', state)
     this.logger.debug('Creating new state entry')
     return this.client.execute(req)
   }
 
-  _createService() {
+  _createService(): Object {
```
Comment (daern91) [inline packages/state-importer/src/main.js]: These ones could be expanded.

File: packages/api-request-builder/src/build-query-string.js [hunk 7]
```diff
@@ -73,7 +75,9 @@ export default function buildQueryString(
       queryString.push(`offset=${offsetParam}`)
     }
     if (sort && sort.length)
-      queryString = queryString.concat(sort.map(s => `sort=${s}`))
+      queryString = queryString.concat(
+        sort.map((s: string): string => `sort=${s}`)
```
Comment (emmenko) [inline packages/api-request-builder/src/build-query-string.js]: In theory this should not be necessary because it's already typed in `ServiceBuilderDefaultParams`.
I'm wondering though if by destructuring it loses the type def.

Can you try removing the destructurings and see if it's correctly typed?

File: packages/csv-parser-discount-code/src/main.js [hunk 8]
```diff
@@ -47,8 +48,8 @@ export default class CsvParserDiscountCode {
   }
 
   // Remove fields with empty values from the code objects
-  static _removeEmptyFields(item: Object) {
-    return Object.keys(item).reduce((acc, key) => {
+  static _removeEmptyFields(item: Object): Object {
```
Comment (emmenko) [inline packages/csv-parser-discount-code/src/main.js]: Observation: typing with `Object` helps only to a certain degree. The more accurate we are with the type, the better we can benefit from its safety.
