### PR TITLE
fix(ts-sdk) Add paths relative to route

### LINKED ISSUE #1469: [typescript-sdk] queryArgs does not define parameters containing dots
### Description

Query args containing `.`'s are missing in the generated types.

See specification for product projection search [here](https://github.com/commercetools/commercetools-api-reference/blob/5e8494ab13d84c6fe132c2a4e8f046a3689a0ca5/resources/product-projections-search.raml#L29):

```yaml
....
 queryParameters:
    fuzzy?:
      type: boolean
      description: Whether to apply fuzzy search on the text to analyze.
    fuzzyLevel?:
      type: number
      description: |
        Provide explicitly the fuzzy level desired if fuzzy is enabled. This value can not be higher than the one
        chosen by the platform by default.
    staged?:
      type: boolean
      description: Whether to query for the current or staged projections.
    filter?:
      type: string
    filter.facets?:
      type: string
    filter.query?:
      type: string
    facet?:
      type: string
.....
```

It contains two query parameters (`filter.query` and `filter.facets`) that are not present in the generated types [here](https://github.com/commercetools/nodejs/blob/70e7ec6ef7d6419952ad924a43298532b1facc9b/packages/typescript-sdk/src/generated/client/search/by-project-key-product-projections-search-request-builder.ts#L38)

```typescript
 public get(methodArgs?: {
    queryArgs?: {
      fuzzy?: boolean | boolean[]
      fuzzyLevel?: number | number[]
      staged?: boolean | boolean[]
      filter?: string | string[]
      facets?: string | string[]
      query?: string | string[]
      facet?: string | string[]
      text?: string | string[]
      sort?: string | string[]
      limit?: number | number[]
      offset?: number | number[]
      withTotal?: boolean | boolean[]
      priceCurrency?: string | string[]
      priceCountry?: string | string[]
      priceCustomerGroup?: string | string[]
      priceChannel?: string | string[]
      expand?: string | string[]
    }
    headers?: {
      [key: string]: string
    }
  }): ApiRequest<ProductProjectionPagedSearchResponse> { ... }
```

### Possible solution

I'm not familiar with kotlin, but it looks like some type of filtering is being applied [here](https://github.com/vrapio/rmf-codegen/blob/2bcc5e21d8f917fa9ddf24c68e430d95fd11f784/languages/typescript/src/main/kotlin/io/vrap/codegen/languages/typescript/client/RequestBuilder.kt#L112)

```
                    var queryParamsArg = ""
                    var bodies = ""
                    if (!it.queryParameters.isEmpty()) {
                        val allQueryParamsOptional = it.queryParameters.map { !it.required }.reduce(Boolean::and)
                        queryParamsArg =
                                """|queryArgs${if (allQueryParamsOptional) "?" else ""}: {
                            |   <${it.queryParameters.map { "'${it.name.tsRemoveRegexp()}'${if (it.required) "" else "?"}: ${it.type.toVrapType().simpleTSName()} | ${it.type.toVrapType().simpleTSName()}[]" }.joinToString(separator = "\n")}>
                            |},""".trimMargin()
                    }
```

I see that the `tsRemoveRegexp` is doing something with strings that contains `.`'s.

```
    if (this.contains(".")) {
        val index = this.indexOf(".")
        return this.substring(index + 1, this.length)
    }
```

### Expected Behavior

I expect that the `queryArgs` type definition should contain all query parameters for the operation.

### LINKED ISSUE #1470: [typescript-sdk] markMatchingVariants is missing from query args type definition
### Description

The type definitions for product projection search is missing the query parameter `markMatchingVariants`. See https://docs.commercetools.com/http-api-projects-products-search#matchingVariant.

The type definition is [here](https://github.com/commercetools/nodejs/blob/master/packages/typescript-sdk/src/generated/client/search/by-project-key-product-projections-search-request-builder.ts#L38):

```typescript
 public get(methodArgs?: {
    queryArgs?: {
      fuzzy?: boolean | boolean[]
      fuzzyLevel?: number | number[]
      staged?: boolean | boolean[]
      filter?: string | string[]
      facets?: string | string[]
      query?: string | string[]
      facet?: string | string[]
      text?: string | string[]
      sort?: string | string[]
      limit?: number | number[]
      offset?: number | number[]
      withTotal?: boolean | boolean[]
      priceCurrency?: string | string[]
      priceCountry?: string | string[]
      priceCustomerGroup?: string | string[]
      priceChannel?: string | string[]
      expand?: string | string[]
    }
    headers?: {
      [key: string]: string
    }
  }): ApiRequest<ProductProjectionPagedSearchResponse> {
```

The RAML spec is also missing the parameter [here](https://github.com/commercetools/commercetools-api-reference/blob/5e8494ab13d84c6fe132c2a4e8f046a3689a0ca5/resources/product-projections-search.raml#L13)

### Expected Behavior

I expect that the parameter should be in the type definition, otherwise I cannot pass it without using some sort of typescript cast.

### PR DESCRIPTION
**Pull request by acbeni**
#### Summary

  Fixes bugs reported by our clients, and take care of introducing our latest Api references updates.

#### Description

This PR closes #1469, and also closes #1470

#### Todo

- Tests
  - [ ] Unit
  - [ ] Integration
  - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: packages/api-request-builder/src/default-params.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ export function getDefaultSearchParams(): ServiceBuilderDefaultParams {
  */
 export function setDefaultParams() {
   this.params.expand = getDefaultQueryParams().expand
-  
+
```
Comment (daern91) [inline packages/api-request-builder/src/default-params.js]: not sure how this one ended up here 😄

File: packages/typescript-sdk/src/ctp/ctp-client.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
-import { middlewareFromCtpClient } from './ctp-middleware'
-import { ApiRoot } from '../generated/client/api-root'
+import { middlewareFromCtpClient } from '~/ctp/ctp-middleware'
+import { ApiRoot } from '~/generated/index'
```
Comment (daern91) [inline packages/typescript-sdk/src/ctp/ctp-client.ts]: ahhh, this is so nice!

File: packages/api-request-builder/src/default-params.js (hunk 1 above)
Comment (acbeni) [reply packages/api-request-builder/src/default-params.js]: I think the git hook doesn't work properly
